version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_management_development
      MYSQL_USER: task_management
      MYSQL_PASSWORD: task_management_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_USERNAME: task_management
      DATABASE_PASSWORD: task_management_password
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["rails", "server", "-b", "0.0.0.0"]

volumes:
  mysql-data:
    driver: local